import Navbar from './components/Navbar'
import './globals.css'
import { Roboto } from 'next/font/google';
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'XenonByte is going on...',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={roboto.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
